# GitterFlow Configuration Example
# Copy this file to .gitterflow.yaml and customize for your project

# Launch mode: "headless" (tmux) or "window" (new editor window)
mode: headless

# AI editor command: "cursor", "code", "cursor-code", "claude-code"
editor: cursor

# Base port for dev servers (auto-increments for each worktree: 3000, 3001, 3002...)
basePort: 3000

# Command to start dev server (runs in pane 1)
# Available environment variables:
#   - GF_BRANCH: Current worktree branch name
#   - GF_BASE_BRANCH: Base branch to merge into
#   - GF_PORT: Assigned port number
#   - GF_WORKTREE_PATH: Absolute path to worktree
devCommand: "bun --hot src/index.ts"

# Base branch to merge back into (auto-detected if not set)
baseBranch: main

# Optional: Custom worktree directory template
# Default: ../<branch-name>
# Use {branch} as placeholder for branch name
worktreePath: "../{branch}"

# Optional: tmux layout
# Options: "even-horizontal", "even-vertical", "main-horizontal", "main-vertical"
tmuxLayout: main-horizontal

# Optional: Terminal emulator to use when opening new worktrees
# macOS: "terminal" (Terminal.app) or "iterm" (iTerm2)
# Linux: "gnome-terminal"
# Windows: "windows-terminal" (Windows Terminal) or "cmd" (Command Prompt)
# Auto-detected on macOS based on TERM_PROGRAM if not set
terminal: iterm
